#!/bin/sh

ROOTDIR=/mnt

mount -o zfsutil -t zfs zroot/ROOT/glibc "$ROOTDIR"

if ! [ -e "$ROOTDIR/chrooted" ]; then
	# chroot has been launched already

	# xchroot commands
	mount --rbind --make-rslave /dev "$ROOTDIR/dev"
	mount --rbind --make-rslave /proc "$ROOTDIR/proc"
	mount --rbind --make-rslave /sys "$ROOTDIR/sys"
	touch "$ROOTDIR/etc/resolv.conf"
	mount --bind /etc/resolv.conf "$ROOTDIR/etc/resolv.conf"

	mount --bind /tmp "$ROOTDIR/tmp"
	mount --bind /home "$ROOTDIR/home"
	mount --rbind --make-rslave /run "$ROOTDIR/run"

	touch "$ROOTDIR/chrooted"
fi

exec pause
